<footer id="footer" class="w-full bg-surface-container-lowest text-on-surface pt-14 sm:pt-16 pb-8 border-t border-surface-container">
<div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8 lg:px-12">
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-10 lg:gap-14 pb-12">
<div class="flex flex-col gap-5">
<a class="inline-flex w-fit" href="/"><img alt="Official FLAME PH logo" class="h-16 w-56 object-cover object-[center_36%]" src="/assets/images/flameph-logo.png"/></a>
<p class="font-body-sm text-body-sm text-on-surface-variant leading-relaxed max-w-xs">Build Ecosystem. Fuel Leaders. Empower Entrepreneurs.</p>
<p class="font-body-sm text-body-sm text-on-surface-variant leading-relaxed max-w-xs">Federation of Leaders Advancing MSME Ecosystem in the Philippines. Championing grassroots enterprise modernization, digital adoption, and market linkage. Regional reach: Update Soon.</p>
<div class="flex items-center gap-5 text-on-surface">
<a aria-label="Share FLAME PH" class="hover:text-primary transition-colors" href="/about#contact"><span class="material-symbols-outlined">share</span></a>
<a aria-label="Email FLAME PH" class="hover:text-primary transition-colors" href="mailto:hello@flameph.org"><span class="material-symbols-outlined">mail</span></a>
<a aria-label="FLAME PH website" class="hover:text-primary transition-colors" href="/"><span class="material-symbols-outlined">public</span></a>
</div>
</div>
<div class="flex flex-col gap-3"><h3 class="font-label-md text-label-md text-on-surface font-bold">Explore FLAME PH</h3><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/">Home</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/about">About FLAME PH</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/membership">Membership Plans</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/directory">MSME Directory</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/community">Community Hubs</a></div>
<div class="flex flex-col gap-3"><h3 class="font-label-md text-label-md text-on-surface font-bold">Resources / Learn</h3><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/learn">Negosyo Starter Kits</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/learn">DTI &amp; BIR Guides</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/learn">Free Templates</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/learn">SME Loan &amp; Grant Kit</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/learn">Webinars &amp; Workshops</a></div>
<div class="flex flex-col gap-3"><h3 class="font-label-md text-label-md text-on-surface font-bold">Community</h3><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="#regional-chapters">Regional Chapters</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="#msme-directory">MSME Directory</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="#regional-chapters">Bayanihan Circles</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/community#summit">FLAME Summit 2025</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/community#mentorship">Mentorship Network</a></div>
<div class="flex flex-col gap-3"><h3 class="font-label-md text-label-md text-on-surface font-bold">Membership &amp; Legal</h3><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/membership#membership-tiers">Free Tier Registration</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/membership#membership-tiers">Neo Member Benefits</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/about#partners">Partner Ecosystem</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/legal#terms">Terms of Service</a><a class="font-body-sm text-body-sm text-on-surface-variant hover:text-primary transition-colors" href="/legal#privacy">Privacy Policy</a></div>
</div>
<div class="border-t border-outline-variant/30 pt-8 text-center"><p class="font-body-sm text-body-sm text-on-surface-variant mb-2">FLAME PH is formerly FAME PH, or Founders' Association of MSMEs and Entrepreneurs. Registration record and source: Update Soon.</p><p class="font-body-sm text-body-sm text-on-surface-variant">© 2025 FLAME PH (Federation of Leaders Advancing MSME Ecosystem in the Philippines). All rights reserved. Ipinagmamalaking gawa ng at para sa negosyanteng Pilipino.</p></div>
<div class="mt-6 border-t border-outline-variant/20 pt-4 text-left text-[11px] leading-relaxed text-on-surface-variant"><p class="font-semibold">Legal Disclaimer &amp; Terms of Use</p><p class="mt-2 font-semibold">Development &amp; Prototype Notice</p><p>Please be advised that the FLAME PH national organization, along with its associated chapter buildups, is currently in an operational development stage. This website functions solely as a prototype and is under active construction. The information, resources, and statements contained within this website are presented exclusively for illustrative and presentation purposes. FLAME PH reserves the right to modify, amend, or update any content without prior notice as the organization advances its structural and partnership development.</p><p class="mt-2 font-semibold">Limitation of Liability</p><p>All content provided on this prototype website is offered on an &quot;as-is&quot; and &quot;as-available&quot; basis, without warranties of any kind, whether express or implied. FLAME PH makes no representations regarding the completeness, accuracy, reliability, or timeliness of any information published herein. In no event shall FLAME PH, its founders, officers, partners, or affiliates be liable for any direct, indirect, incidental, or consequential damages arising out of or in connection with the use of, or inability to use, this website or reliance on any information provided.</p><p class="mt-2 font-semibold">Privacy Notice</p><p>As this platform is currently a prototype, any information collected through form submissions, analytics, or website interactions is handled strictly for testing and organizational development purposes. FLAME PH does not sell, rent, or trade personal data to third parties. By interacting with this website, you acknowledge and consent to the temporary collection and processing of operational data necessary to refine and build out the FLAME PH platform.</p></div>
</div>
</footer>
