<style>body > footer:not(.site-footer) { display: none; }</style>
<footer id="footer" class="site-footer w-full bg-[#061b3b] text-white">
    <div class="mx-auto max-w-7xl px-4 pb-8 pt-14 sm:px-6 lg:px-8">
        <div class="grid gap-10 border-b border-white/15 pb-12 lg:grid-cols-12 lg:gap-14">
            <div class="lg:col-span-4">
                <a class="inline-flex" href="/"><img src="/assets/images/flameph-logo.png" alt="FLAME PH logo" class="h-14 w-52 object-cover object-[center_36%]"></a>
                <p class="mt-5 font-headline text-lg font-bold text-[#ffddb8]">Build Ecosystem. Fuel Leaders. Empower Entrepreneurs.</p>
                <p class="mt-3 max-w-md text-sm leading-6 text-white/75">Federation of Leaders Advancing MSME Ecosystem in the Philippines. Connecting Filipino entrepreneurs with practical learning, trusted partners, and sustainable growth opportunities.</p>
                <div class="mt-6 rounded-2xl bg-white/10 p-5">
                    <h3 class="font-semibold text-white">MSME Bulletin Newsletter</h3>
                    <p class="mt-1 text-sm text-white/65">Get business resources, events, and community updates.</p>
                    <form class="mt-4 flex gap-2" action="#footer" method="get"><label class="sr-only" for="footer-email">Business email</label><input id="footer-email" class="min-w-0 flex-1 rounded-lg border-0 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-500 focus:ring-2 focus:ring-[#ffddb8]" name="email" placeholder="Enter business email" type="email"><button class="rounded-lg bg-secondary px-4 py-2 text-sm font-bold text-white hover:bg-secondary-container" type="submit">Subscribe</button></form>
                </div>
            </div>
            <div class="grid grid-cols-2 gap-x-6 gap-y-10 sm:grid-cols-3 lg:grid-cols-5 lg:col-span-8">
                <div class="flex flex-col gap-3"><h3 class="text-xs font-bold uppercase tracking-wider text-[#ffddb8]">What We Do</h3><a class="text-sm text-white/70 hover:text-white" href="/programs-ecosystem">Programs &amp; MSME Ecosystem</a><a class="text-sm text-white/70 hover:text-white" href="/events">Educational Workshops</a><a class="text-sm text-white/70 hover:text-white" href="/learn">Trainings &amp; Webinars</a><a class="text-sm text-white/70 hover:text-white" href="/events">Expos &amp; Summits</a><a class="text-sm text-white/70 hover:text-white" href="/events#awards">Annual Awards for MSMEs</a></div>
                <div class="flex flex-col gap-3"><h3 class="text-xs font-bold uppercase tracking-wider text-[#ffddb8]">Membership</h3><a class="text-sm text-white/70 hover:text-white" href="/membership/free-benefits">Avail Free MSME Benefits</a><a class="text-sm text-white/70 hover:text-white" href="/membership/more-benefits">Get More MSME Benefits</a><a class="text-sm text-white/70 hover:text-white" href="/learn">Resources</a><a class="text-sm text-white/70 hover:text-white" href="/about">Advocacy</a><a class="text-sm text-white/70 hover:text-white" href="/directory">Chapters Near You</a><a class="text-sm text-white/70 hover:text-white" href="/directory">Featured Members</a><a class="text-sm text-white/70 hover:text-white" href="/events">Volunteering</a><a class="text-sm text-white/70 hover:text-white" href="/learn">Free POS for MSMEs</a><a class="text-sm text-white/70 hover:text-white" href="/directory">Free Business Directory</a><a class="text-sm text-white/70 hover:text-white" href="/about#contact">Free Consultation @ Flame AI</a></div>
                <div class="flex flex-col gap-3"><h3 class="text-xs font-bold uppercase tracking-wider text-[#ffddb8]">Support Us</h3><a class="text-sm text-white/70 hover:text-white" href="/flameph-merchs">FLAME PH Merchs</a><a class="text-sm text-white/70 hover:text-white" href="/about/merch-shop">Flame Signature Brands</a><a class="text-sm text-white/70 hover:text-white" href="/about/merch-shop">Personalized by FLAMEPH</a><a class="text-sm text-white/70 hover:text-white" href="/about/merch-shop">Shop or Sell @ MarketplacePH</a><a class="text-sm text-white/70 hover:text-white" href="/about/merch-shop">Start &amp; Grow @ NegosyoDepot</a><a class="text-sm text-white/70 hover:text-white" href="/about/merch-shop">Fulfillment by MSMEs</a></div>
                <div class="flex flex-col gap-3"><h3 class="text-xs font-bold uppercase tracking-wider text-[#ffddb8]">Get Involved</h3><a class="text-sm text-white/70 hover:text-white" href="/get-involved">Volunteer as Mentor</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved">Join as Partner</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved">Sponsor an Event</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved">Sponsor a Community</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved">Nominate an MSME Awardee</a><a class="text-sm text-white/70 hover:text-white" href="/about#contact">Support Poverty Alleviation Program</a><a class="text-sm text-white/70 hover:text-white" href="/events">News &amp; Updates</a><a class="text-sm text-white/70 hover:text-white" href="/flameph-merchs">Become an Affiliate Marketer</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved#community">Become a Chapter Leader</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved#mentor">Volunteer as a Resource Speaker</a><a class="text-sm text-white/70 hover:text-white" href="/get-involved#partners">Volunteer Professional Services</a></div>
                <div class="flex flex-col gap-3"><h3 class="text-xs font-bold uppercase tracking-wider text-[#ffddb8]">About Us</h3><a class="text-sm text-white/70 hover:text-white" href="/about">What is FLAME PH</a><a class="text-sm text-white/70 hover:text-white" href="/about#founders">Meet the Founders</a><a class="text-sm text-white/70 hover:text-white" href="/about#teams">Meet the Teams</a><a class="text-sm text-white/70 hover:text-white" href="/directory">Featured Chapters</a><a class="text-sm text-white/70 hover:text-white" href="/directory">Featured Members</a><a class="text-sm text-white/70 hover:text-white" href="/about#partners">Featured Partners</a></div>
            </div>
        </div>
        <div class="flex flex-col gap-4 pt-6 text-sm text-white/60 md:flex-row md:items-center md:justify-between"><p>© 2025 FLAME PH. Start local. Grow together. Scale global.</p><div class="flex flex-wrap gap-x-5 gap-y-2"><a class="hover:text-white" href="/legal#terms">Terms of Use</a><a class="hover:text-white" href="/legal#privacy">Privacy Notice</a><a class="hover:text-white" href="mailto:hello@flameph.org">hello@flameph.org</a></div></div>
        <div class="mt-6 border-t border-white/10 pt-4 text-left text-[11px] leading-relaxed text-white/45"><p>FLAME PH is a prototype platform under active development. Information is provided for general educational and community purposes; verify legal, tax, financing, and regulatory requirements with the relevant official source.</p></div>
    </div>
</footer>
