<div class="space-y-7 text-sm leading-7 text-[#434653]">
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">1. Membership and scope</h2><p class="mt-2">FLAME PH Free Community membership is intended to connect aspiring and operating entrepreneurs with learning, community activities, and MSME ecosystem opportunities. Membership does not guarantee funding, customers, permits, business success, professional advice, or access to any particular partner service. Activities and benefits may change as the organization develops.</p></section>
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">2. Honest and responsible participation</h2><p class="mt-2">Members must provide information honestly, use FLAME PH names and materials only with authorization, respect other members, and comply with applicable laws and event rules. A member is responsible for their own statements, representations, transactions, and unlawful or unscrupulous conduct. A member must not claim to speak for FLAME PH or a chapter unless authorized.</p><p class="mt-2">A member’s unauthorized conduct or misrepresentation is not automatically an act or representation of FLAME PH or a chapter. FLAME PH may review reports and may suspend or end membership for misuse, harmful conduct, or serious violations. Nothing here removes responsibility for an organization or person’s own acts, omissions, or duties imposed by law.</p></section>
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">3. Communications and marketing choices</h2><p class="mt-2">FLAME PH may send essential membership and service messages needed to administer membership. Separate, optional marketing consent may be given at registration for FLAME PH newsletters and marketing, partner MSME and brand offers, and invitations or updates about meetings (including Google Meet or Zoom) and webinars. Channels may include email, SMS, and Facebook Messenger.</p><p class="mt-2">Marketing consent is optional and is not required to join. A member may withdraw it at any time by using an unsubscribe option where provided or by emailing <a class="font-bold text-[#003289] underline" href="mailto:federationofmsmes@gmail.com">federationofmsmes@gmail.com</a>. Withdrawal does not affect processing necessary for membership administration or messages already sent. Partner communications will be limited to the consent and privacy notices applicable to the relevant activity.</p></section>
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">4. Personal information</h2><p class="mt-2">FLAME PH uses membership information to administer the community, tailor resources, respond to inquiries, and—only where separately selected—send marketing communications. Members should provide only information they are comfortable sharing and should not submit passwords, payment credentials, or unnecessary sensitive information through website forms. Personal information is handled subject to applicable privacy law and the FLAME PH privacy notice. Members may contact FLAME PH at the email above with privacy questions or requests.</p></section>
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">5. Events, partners, and member interactions</h2><p class="mt-2">Members participate in meetings, webinars, referrals, and interactions with other members or partner businesses at their own discretion. Verify offers, credentials, costs, and terms independently before sharing information, paying money, or entering into a transaction. FLAME PH does not endorse or guarantee every third-party product or outcome unless it expressly says so in writing.</p></section>
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">6. Responsibility and limits</h2><p class="mt-2">Each member is responsible for their own conduct and for any claims, commitments, or representations they make. FLAME PH is not responsible merely because a person is a member or belongs to a chapter for conduct that the person undertakes without FLAME PH authorization or participation. FLAME PH and its officers remain responsible for their own acts and obligations to the extent required by law. Nothing in these terms is intended to exclude liability that cannot legally be excluded, limit statutory rights, or waive remedies for fraud, willful misconduct, or other non-waivable responsibility.</p></section>
    <section><h2 class="text-xl font-extrabold text-[#131b2e]">7. Changes, suspension, and questions</h2><p class="mt-2">FLAME PH may update these terms as its programs develop. Material changes will be presented for review where required. Continued participation after notice of an update may require renewed acceptance. FLAME PH may suspend or terminate membership for a serious breach, subject to applicable law and fair process appropriate to the circumstances. For questions, email <a class="font-bold text-[#003289] underline" href="mailto:federationofmsmes@gmail.com">federationofmsmes@gmail.com</a>.</p></section>
    <p class="border-t border-[#e2e7ff] pt-5 text-xs text-[#737685]">Version 1.0 • Effective September 27, 2026. These terms are a practical membership draft and should be reviewed by qualified Philippine counsel before formal organizational adoption.</p>
</div>
