<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="FLAME PH connects Filipino entrepreneurs with practical learning, trusted business connections, and a community built to help MSMEs grow.">
    <title>FLAME PH | Grow your Filipino business together</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <script>tailwind.config={theme:{extend:{colors:{primary:'#003289','primary-container':'#0047ba',secondary:'#bc000c','secondary-container':'#e81218',surface:'#faf8ff','surface-container-low':'#f2f3ff','surface-container-high':'#e2e7ff','on-surface':'#131b2e','on-surface-variant':'#434653','tertiary-fixed':'#ffddb8','tertiary-container':'#724700'},fontFamily:{body:['Inter'],headline:['Plus Jakarta Sans']}}}};</script>
    <style>html{scroll-behavior:smooth}body{margin:0;overflow-x:hidden}.font-headline{font-family:'Plus Jakarta Sans',sans-serif}.font-body{font-family:Inter,sans-serif}.material-symbols-outlined{font-variation-settings:'FILL' 0,'wght' 500,'GRAD' 0,'opsz' 24}</style>
</head>
<body class="bg-surface text-on-surface font-body">
<header data-site-header class="fixed inset-x-0 top-0 z-50 bg-white/95 shadow-sm backdrop-blur-xl">
    <div class="bg-primary px-4 py-2 text-center text-xs font-semibold text-white sm:text-sm">Unite Filipino MSMEs • Grow Together • Build a Stronger Philippines <a class="ml-2 text-tertiary-fixed underline" href="/membership#registration">Join FLAME PH Free →</a></div>
    <div class="mx-auto flex h-20 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        <a href="/" aria-label="FLAME PH home"><img src="/assets/images/flameph-logo.png" alt="FLAME PH" class="h-12 w-44 object-cover object-[center_36%]"></a>
        <nav aria-label="Primary navigation" class="hidden items-center gap-1 xl:flex"><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/learn">What We Do</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/membership">Membership</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/about/merch-shop">Support Us</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/events">Get Involved</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/about">About Us</a></nav>
        <div class="flex items-center gap-2"><a class="hidden rounded-lg px-3 py-2 font-semibold text-primary sm:inline-flex" href="/membership#login">Log in</a><a class="rounded-full bg-secondary px-4 py-2.5 font-semibold text-white shadow-md hover:bg-secondary-container" href="/membership#registration">Join free →</a><button data-site-menu-toggle aria-label="Open navigation menu" aria-expanded="false" aria-controls="site-mobile-menu" class="inline-flex h-10 w-10 items-center justify-center rounded-lg text-primary hover:bg-surface-container-low xl:hidden" type="button"><span data-site-menu-icon class="material-symbols-outlined">menu</span></button></div>
    </div>
</header>
<main class="pt-28 sm:pt-32">
    <section class="bg-gradient-to-b from-surface-container-low to-surface px-4 py-12 sm:px-6 sm:py-20 lg:px-8"><div class="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-12 lg:gap-16"><div class="lg:col-span-7"><span class="inline-flex rounded-full bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-primary shadow-sm">🇵🇭 Official Philippine MSME Ecosystem • Free Membership</span><h1 class="mt-6 font-headline text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl lg:text-6xl">Hindi mo kailangang mag-start at mag-grow ng business nang <span class="text-primary">mag-isa.</span></h1><p class="mt-6 max-w-2xl text-lg leading-8 text-on-surface-variant">FLAME PH connects aspiring entrepreneurs and MSMEs with practical learning, trusted business connections, and a growing ecosystem built for the changing, AI-shaped economy.</p><div class="mt-8 flex flex-col gap-3 sm:flex-row"><a class="inline-flex items-center justify-center rounded-full bg-secondary px-7 py-4 font-semibold text-white shadow-lg hover:bg-secondary-container" href="/membership#registration">Join FLAME PH Free →</a><a class="inline-flex items-center justify-center gap-2 rounded-full bg-white px-7 py-4 font-semibold text-primary shadow-sm hover:bg-surface-container" href="/learn"><span class="material-symbols-outlined">menu_book</span>Explore the Learning Hub</a></div><div class="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold text-on-surface-variant"><span>✓ Free to join</span><span>✓ Practical resources</span><span>✓ Filipino-led community</span></div></div><div class="lg:col-span-5"><div class="relative overflow-hidden rounded-3xl bg-primary p-7 text-white shadow-2xl"><div class="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-white/10 blur-2xl"></div><p class="relative text-sm font-bold uppercase tracking-widest text-tertiary-fixed">Start where you are</p><h2 class="relative mt-3 font-headline text-3xl font-extrabold">Build better business habits with people who understand the journey.</h2><div class="relative mt-8 grid grid-cols-2 gap-3 text-sm"><div class="rounded-2xl bg-white/10 p-4"><strong class="block text-2xl">{{ number_format($membershipStats['registered_members']) }}</strong>registered members</div><div class="rounded-2xl bg-white/10 p-4"><strong class="block text-2xl">{{ number_format($membershipStats['chapter_locations']) }}</strong>local connections</div></div><a class="relative mt-8 inline-flex font-semibold text-tertiary-fixed underline" href="/membership">See membership options →</a></div></div></div></section>
    <section class="bg-white px-4 py-16 sm:px-6 lg:px-8"><div class="mx-auto max-w-7xl"><div class="mx-auto max-w-3xl text-center"><span class="rounded-full bg-surface-container-high px-4 py-2 text-xs font-bold uppercase tracking-wider text-primary">The FLAME Principle</span><h2 class="mt-5 font-headline text-3xl font-extrabold tracking-tight sm:text-4xl">One MSME alone pays more. Together, we can pay less and grow more.</h2><p class="mt-4 text-on-surface-variant">Small Filipino enterprises unlock stronger connections, shared learning, and better opportunities through community.</p></div><div class="mt-10 grid gap-6 md:grid-cols-2"><div class="rounded-3xl bg-surface-container-low p-7"><div class="flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-full bg-red-100 text-secondary"><span class="material-symbols-outlined">person_off</span></span><div><span class="text-xs font-bold uppercase tracking-wider text-on-surface-variant">Traditional method</span><h3 class="font-headline text-2xl font-bold">Operating alone</h3></div></div><p class="mt-5 text-on-surface-variant">Solo operators shoulder full retail markups, isolated risks, and costly technology friction without peer support.</p><ul class="mt-6 space-y-3 text-sm"><li class="rounded-xl bg-white p-4">✕ High procurement and packaging costs</li><li class="rounded-xl bg-white p-4">✕ Limited referrals and market reach</li><li class="rounded-xl bg-white p-4">✕ Fragmented tools and advisory support</li></ul></div><div class="rounded-3xl bg-gradient-to-br from-primary to-primary-container p-7 text-white shadow-xl"><div class="flex items-center gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-full bg-white text-primary"><span class="material-symbols-outlined">handshake</span></span><div><span class="text-xs font-bold uppercase tracking-wider text-tertiary-fixed">The bayanihan advantage</span><h3 class="font-headline text-2xl font-bold">With FLAME PH</h3></div></div><p class="mt-5 text-white/85">Connect with Filipino entrepreneurs to learn faster, find trusted suppliers, and discover practical pathways to grow.</p><ul class="mt-6 space-y-3 text-sm"><li class="rounded-xl bg-white/10 p-4">✓ Community-led learning and referrals</li><li class="rounded-xl bg-white/10 p-4">✓ A directory for local suppliers and partners</li><li class="rounded-xl bg-white/10 p-4">✓ Shared opportunities for sustainable growth</li></ul></div></div></div></section>
    <section class="bg-surface px-4 py-16 sm:px-6 lg:px-8"><div class="mx-auto max-w-7xl"><div class="mx-auto max-w-3xl text-center"><span class="text-xs font-bold uppercase tracking-widest text-primary">One integrated ecosystem</span><h2 class="mt-3 font-headline text-3xl font-extrabold sm:text-4xl">Many growth pathways</h2><p class="mt-4 text-on-surface-variant">Choose the support that fits your next step.</p></div><div class="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><a class="rounded-2xl bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md" href="/learn"><span class="material-symbols-outlined text-3xl text-primary">menu_book</span><h3 class="mt-4 font-headline text-xl font-bold">Learn</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">Free guides, templates, and business lessons made for Filipino entrepreneurs.</p></a><a class="rounded-2xl bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md" href="/directory"><span class="material-symbols-outlined text-3xl text-secondary">contacts</span><h3 class="mt-4 font-headline text-xl font-bold">Connect</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">Find members, suppliers, and partners across the Philippines.</p></a><a class="rounded-2xl bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md" href="/events"><span class="material-symbols-outlined text-3xl text-tertiary-container">groups</span><h3 class="mt-4 font-headline text-xl font-bold">Join in</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">Discover events, workshops, and community conversations.</p></a><a class="rounded-2xl bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md" href="/membership"><span class="material-symbols-outlined text-3xl text-primary">trending_up</span><h3 class="mt-4 font-headline text-xl font-bold">Grow</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">Start with free membership and unlock more support as you grow.</p></a></div></div></section>
    <section class="bg-white px-4 py-16 sm:px-6 lg:px-8"><div class="mx-auto max-w-7xl"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><span class="text-xs font-bold uppercase tracking-widest text-secondary">Zero barriers</span><h2 class="mt-2 font-headline text-3xl font-extrabold">Start where you are</h2></div><a class="font-semibold text-primary hover:underline" href="/learn">View all resources →</a></div><div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><a class="rounded-2xl bg-surface-container-low p-5" href="/membership"><h3 class="font-headline text-lg font-bold">Join Free Now</h3><p class="mt-2 text-sm text-on-surface-variant">₱0 registration fee and a simple first step into the ecosystem.</p></a><a class="rounded-2xl bg-surface-container-low p-5" href="/directory"><h3 class="font-headline text-lg font-bold">Find Members</h3><p class="mt-2 text-sm text-on-surface-variant">Browse entrepreneurs, suppliers, and partners near you.</p></a><a class="rounded-2xl bg-surface-container-low p-5" href="/learn"><h3 class="font-headline text-lg font-bold">Free Guides</h3><p class="mt-2 text-sm text-on-surface-variant">Download practical checklists, templates, and learning modules.</p></a><a class="rounded-2xl bg-surface-container-low p-5" href="/events"><h3 class="font-headline text-lg font-bold">Join a Chapter</h3><p class="mt-2 text-sm text-on-surface-variant">Connect with grassroots leaders and local business communities.</p></a></div></div></section>
    <section class="bg-primary px-4 py-16 text-center text-white sm:px-6 lg:px-8"><div class="mx-auto max-w-4xl"><span class="text-xs font-bold uppercase tracking-widest text-tertiary-fixed">Growing Filipino MSMEs together</span><h2 class="mt-4 font-headline text-3xl font-extrabold sm:text-5xl">Hindi mo kailangang mag-isa.</h2><p class="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/85">Sumama sa komunidad ng mga negosyanteng Pilipino. Join free, learn free, and grow together.</p><a class="mt-8 inline-flex rounded-full bg-secondary px-8 py-4 font-bold text-white shadow-lg hover:bg-secondary-container" href="/membership#registration">Join FLAME PH Free →</a></div></section>
</main>
@include('partials.home-footer')
@include('partials.mobile-navigation')
</body>
</html>
