<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Explore FLAME PH programs and the MSME ecosystem helping Filipino entrepreneurs start, grow, sustain, scale, and go global.">
    <title>Programs &amp; MSME Ecosystem | FLAME PH</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
    <script>tailwind.config={theme:{extend:{colors:{primary:'#003289','primary-container':'#0047ba',secondary:'#bc000c','secondary-container':'#e81218',surface:'#faf8ff','surface-container-low':'#f2f3ff','surface-container':'#eaedff','surface-container-high':'#e2e7ff','on-surface':'#131b2e','on-surface-variant':'#434653','tertiary-fixed':'#ffddb8','tertiary-container':'#724700'},fontFamily:{body:['Inter'],headline:['Plus Jakarta Sans']}}}};</script>
    <style>html{scroll-behavior:smooth}body{margin:0;overflow-x:hidden}.font-headline{font-family:'Plus Jakarta Sans',sans-serif}.font-body{font-family:Inter,sans-serif}.material-symbols-outlined{font-variation-settings:'FILL' 0,'wght' 500,'GRAD' 0,'opsz' 24}</style>
</head>
<body class="bg-surface text-on-surface font-body">
<header data-site-header class="fixed inset-x-0 top-0 z-50 bg-white/95 shadow-sm backdrop-blur-xl">
    <div class="bg-primary px-4 py-2 text-center text-xs font-semibold text-white sm:text-sm"><span style="font-family:'Arial Narrow', Arial, sans-serif; font-weight:400; text-decoration:none">Disclaimer: FLAME PH is a work in progress; its content, features, and ecosystem is evolving over time, with updates reflected on this website. Founders & Leaders: Join us in building the FLAMEPH ecosystem and FLAMEPH chapters nationwide.</span></div>
    <div class="mx-auto flex h-20 max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
        <a href="/" aria-label="FLAME PH home"><img src="/assets/images/flameph-logo.png" alt="FLAME PH" class="h-12 w-44 object-cover object-[center_36%]"></a>
        <nav aria-label="Primary navigation" class="hidden items-center gap-1 xl:flex"><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/programs-ecosystem">What We Do</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/membership/free-benefits">Membership</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/flameph-merchs">Support Us</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/get-involved">Get Involved</a><a class="rounded-xl px-3 py-2 text-on-surface-variant hover:bg-surface-container-low hover:text-primary" href="/about">About Us</a></nav>
        <div class="flex items-center gap-2"><a class="hidden rounded-lg px-3 py-2 font-semibold text-primary sm:inline-flex" href="/membership#login">Log in</a><a class="rounded-full bg-secondary px-4 py-2.5 font-semibold text-white shadow-md hover:bg-secondary-container" href="/membership#registration">Join free →</a><button data-site-menu-toggle aria-label="Open navigation menu" aria-expanded="false" aria-controls="site-mobile-menu" class="inline-flex h-10 w-10 items-center justify-center rounded-lg text-primary hover:bg-surface-container-low xl:hidden" type="button"><span data-site-menu-icon class="material-symbols-outlined">menu</span></button></div>
    </div>
</header>
<main class="pt-28 sm:pt-32">
    <section class="relative overflow-hidden bg-surface-container-low px-4 py-14 sm:px-6 sm:py-20 lg:px-8">
        <div class="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-primary/10 blur-3xl"></div>
        <div class="relative mx-auto flex max-w-5xl flex-col items-center text-center">
            <span class="inline-flex rounded-full bg-white px-4 py-2 text-xs font-bold uppercase tracking-wider text-primary shadow-sm">Programs &amp; Ecosystem Overview • FLAME PH</span>
            <h1 class="mt-6 max-w-5xl font-headline text-4xl font-extrabold leading-tight tracking-tight text-primary sm:text-5xl lg:text-6xl">We build the conditions for Filipino MSMEs to start, grow, sustain, <span class="text-primary-container">scale, and go global.</span></h1>
            <p class="mt-6 max-w-3xl text-lg leading-8 text-on-surface-variant">FLAME PH combines entrepreneurship education, digital adoption, AI copilot tooling, collaborative referrals, shared demand, market linkages, professional mentorship, grassroots chapters, and nationwide partnerships.</p>
            <div class="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a class="inline-flex items-center justify-center rounded-full bg-secondary px-7 py-4 font-bold text-white shadow-lg hover:bg-secondary-container" href="/membership#registration">Join FLAME PH Free →</a><a class="inline-flex items-center justify-center rounded-full bg-white px-7 py-4 font-bold text-primary shadow-sm hover:bg-surface-container" href="#primary-programs">Find a Program <span class="material-symbols-outlined ml-2 text-lg">south</span></a></div>
            <div class="mt-10 grid w-full max-w-5xl grid-cols-2 gap-4 rounded-2xl bg-white p-4 text-left shadow-md md:grid-cols-4"><div class="border-b px-3 py-2 md:border-b-0 md:border-r"><strong class="block text-3xl text-primary">82+</strong><span class="text-sm font-semibold text-on-surface-variant">Regional Chapters Active</span></div><div class="border-b px-3 py-2 md:border-b-0 md:border-r"><strong class="block text-3xl text-secondary">15,000+</strong><span class="text-sm font-semibold text-on-surface-variant">MSME Members Nationwide</span></div><div class="px-3 py-2 md:border-r"><strong class="block text-3xl text-tertiary-container">₱42M+</strong><span class="text-sm font-semibold text-on-surface-variant">Shared Cost Savings</span></div><div class="px-3 py-2"><strong class="block text-3xl text-primary-container">100+</strong><span class="text-sm font-semibold text-on-surface-variant">Masterclass Workshops</span></div></div>
        </div>
    </section>
    <section id="primary-programs" class="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8">
        <div class="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><span class="text-xs font-bold uppercase tracking-widest text-secondary">Cornerstone initiatives</span><h2 class="mt-2 font-headline text-3xl font-extrabold sm:text-4xl">Four Pillars of Grassroots Power</h2></div><p class="max-w-md text-on-surface-variant">Structured acceleration architecture engineered for micro, small, and medium commercial builders across all islands.</p></div>
        <div class="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
            <a href="/membership" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-primary/5 transition hover:-translate-y-1 hover:shadow-lg"><span class="inline-flex rounded-full bg-primary/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-primary">Core acceleration</span><span class="mt-5 flex h-12 w-12 items-center justify-center rounded-xl bg-surface-container text-primary"><span class="material-symbols-outlined">point_of_sale</span></span><h3 class="mt-5 font-headline text-xl font-bold">Programs for MSMEs</h3><p class="mt-3 text-sm leading-6 text-on-surface-variant">Access Free POS, FLAME AI copilot, verified directory listings, and combined vendor buying power.</p><span class="mt-6 inline-flex font-bold text-primary group-hover:underline">Explore MSME Programs →</span></a>
            <a href="/events" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-primary/5 transition hover:-translate-y-1 hover:shadow-lg"><span class="inline-flex rounded-full bg-secondary/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-secondary">Capacity building</span><span class="mt-5 flex h-12 w-12 items-center justify-center rounded-xl bg-surface-container text-secondary"><span class="material-symbols-outlined">school</span></span><h3 class="mt-5 font-headline text-xl font-bold">Advocacy Workshops</h3><p class="mt-3 text-sm leading-6 text-on-surface-variant">Hands-on regional training in bookkeeping, taxation, e-commerce, modern marketing, and AI adoption.</p><span class="mt-6 inline-flex font-bold text-secondary group-hover:underline">View Workshop Schedule →</span></a>
            <a href="/events" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-primary/5 transition hover:-translate-y-1 hover:shadow-lg"><span class="inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-bold uppercase tracking-wider text-tertiary-container">Market linkages</span><span class="mt-5 flex h-12 w-12 items-center justify-center rounded-xl bg-surface-container text-tertiary-container"><span class="material-symbols-outlined">storefront</span></span><h3 class="mt-5 font-headline text-xl font-bold">Expos &amp; Summits</h3><p class="mt-3 text-sm leading-6 text-on-surface-variant">B2B matching, trade fairs, franchise showcases, and conventions connecting local producers to buyers.</p><span class="mt-6 inline-flex font-bold text-tertiary-container group-hover:underline">Discover Upcoming Expos →</span></a>
            <a href="/events#awards" class="group rounded-2xl bg-white p-6 shadow-sm ring-1 ring-primary/5 transition hover:-translate-y-1 hover:shadow-lg"><span class="inline-flex rounded-full bg-surface-container-high px-3 py-1 text-xs font-bold uppercase tracking-wider text-primary">Recognition &amp; grants</span><span class="mt-5 flex h-12 w-12 items-center justify-center rounded-xl bg-surface-container text-primary"><span class="material-symbols-outlined">military_tech</span></span><h3 class="mt-5 font-headline text-xl font-bold">Annual Awards</h3><p class="mt-3 text-sm leading-6 text-on-surface-variant">Honor resilience, innovation, job generation, and women-led enterprises with grants and national publicity.</p><span class="mt-6 inline-flex font-bold text-primary group-hover:underline">Nominate an MSME Awardee →</span></a>
        </div>
    </section>
    <section class="mx-auto grid max-w-7xl gap-5 px-4 pb-14 sm:px-6 md:grid-cols-3 lg:px-8"><div class="relative h-64 overflow-hidden rounded-2xl shadow-sm"><img class="h-full w-full object-cover" src="/assets/images/home/flameph-business-flow.png" alt="Filipino business owners connecting at a FLAME PH event"><div class="absolute inset-x-0 bottom-0 bg-gradient-to-t from-primary/90 p-5 pt-12 text-sm font-bold text-white">Grassroots producers reaching urban markets</div></div><div class="relative h-64 overflow-hidden rounded-2xl shadow-sm"><img class="h-full w-full object-cover" src="/assets/images/home/flameph-learning-to-earning.png" alt="Filipino entrepreneurs learning practical digital tools"><div class="absolute inset-x-0 bottom-0 bg-gradient-to-t from-primary/90 p-5 pt-12 text-sm font-bold text-white">Modern digital adoption</div></div><div class="relative h-64 overflow-hidden rounded-2xl shadow-sm"><img class="h-full w-full object-cover" src="/assets/images/home/flameph-local-to-global.png" alt="A Filipino business growing through community support"><div class="absolute inset-x-0 bottom-0 bg-gradient-to-t from-primary/90 p-5 pt-12 text-sm font-bold text-white">Local brands reaching global markets</div></div></section>
    <section class="bg-white px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div class="mx-auto max-w-7xl"><div class="mx-auto mb-10 max-w-3xl text-center"><span class="text-xs font-bold uppercase tracking-widest text-secondary">Lifecycle architecture</span><h2 class="mt-2 font-headline text-3xl font-extrabold text-primary sm:text-4xl">The FLAME PH Continuous Growth Cycle</h2><p class="mt-3 text-on-surface-variant">How individual Filipino negosyantes unite into a resilient collective economic force through step-by-step institutional backing.</p></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">@foreach([['Educate','Masterclasses, compliance guidance, and practical AI coaching.'],['Connect','Local chapters, peer circles, and vetted vendor directories.'],['Start Earning','Digital catalogs and member-driven promotional leads.'],['Build Business','Free cloud POS, inventory systems, and formalization.'],['Create Jobs','Expand production and increase local community impact.'],['Scale Brands','Nationwide distribution and export acceleration.']] as $index => $step)<div class="rounded-2xl bg-surface p-5 shadow-sm"><span class="flex h-8 w-8 items-center justify-center rounded-full {{ $index === 2 ? 'bg-secondary' : ($index === 5 ? 'bg-tertiary-container' : 'bg-primary') }} text-sm font-bold text-white">{{ $index + 1 }}</span><h3 class="mt-4 font-headline text-lg font-bold">{{ $step[0] }}</h3><p class="mt-2 text-sm leading-6 text-on-surface-variant">{{ $step[1] }}</p></div>@endforeach</div></div></section>
    <section class="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div class="mx-auto mb-8 max-w-2xl text-center"><span class="text-xs font-bold uppercase tracking-widest text-secondary">Tailored onboarding</span><h2 class="mt-2 font-headline text-3xl font-extrabold sm:text-4xl">Explore What Fits You</h2><p class="mt-3 text-on-surface-variant">Choose your profile to see curated resources, acceleration programs, and immediate perks.</p></div><div class="flex flex-wrap justify-center gap-2" role="tablist" aria-label="Audience pathways">@foreach(['aspiring'=>'Aspiring Entrepreneur','existing'=>'Existing MSME Owner','professional'=>'Professional & Expert','mentor'=>'Mentor & Speaker','corporate'=>'Corporate Partner / Sponsor','chapter'=>'Chapter Builder'] as $key => $label)<button type="button" class="audience-tab rounded-full bg-surface-container-high px-4 py-2.5 text-sm font-bold text-on-surface transition hover:bg-primary hover:text-white {{ $loop->first ? 'is-active !bg-primary !text-white' : '' }}" data-audience="{{ $key }}" role="tab">{{ $label }}</button>@endforeach</div><div id="audience-content" class="mx-auto mt-6 max-w-4xl rounded-2xl bg-white p-6 shadow-md sm:p-8"><span class="text-xs font-bold uppercase tracking-wider text-secondary">For new founders &amp; side-hustlers</span><h3 id="audience-title" class="mt-2 font-headline text-2xl font-extrabold text-primary">Turn Your Idea Into a Profitable Enterprise</h3><p id="audience-description" class="mt-3 leading-7 text-on-surface-variant">Receive straightforward roadmaps for registration, product costing, supplier matchmaking, and free AI marketing copy generators.</p><a id="audience-link" class="mt-6 inline-flex rounded-full bg-secondary px-5 py-3 font-bold text-white" href="/membership#registration">Launch Your Business →</a></div></section>
    <section class="bg-surface-container px-4 py-14 sm:px-6 sm:py-20 lg:px-8"><div class="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-2"><div><span class="inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-bold uppercase tracking-wider text-tertiary-container">Co-op demand power</span><h2 class="mt-4 font-headline text-3xl font-extrabold text-primary sm:text-4xl">“One MSME pays more. Together, we pay less.”</h2><p class="mt-4 text-lg leading-8 text-on-surface-variant">FLAME PH pools member demand nationwide to unlock better pricing for packaging, courier logistics, raw ingredients, and technology.</p><a class="mt-6 inline-flex font-bold text-primary hover:underline" href="/about/merch-shop">View NegosyoDepot cooperative procurement →</a></div><div class="rounded-2xl bg-white p-6 shadow-md"><div class="flex items-center justify-between border-b pb-4"><strong>Cooperative Demand Aggregation Engine</strong><span class="rounded-full bg-secondary/10 px-2 py-1 text-xs font-bold text-secondary">Live group buys</span></div>@foreach([['Eco-Kraft Pouches','82%'],['Cold Chain Delivery','94%'],['Custom Label Printing','68%']] as $item)<div class="mt-5"><div class="flex justify-between text-sm"><span>{{ $item[0] }}</span><strong class="text-primary">{{ $item[1] }}</strong></div><div class="mt-2 h-2.5 rounded-full bg-surface-container"><div class="h-2.5 rounded-full bg-primary" style="width: {{ $item[1] }}"></div></div></div>@endforeach</div></div></section>
    <section class="bg-primary px-4 py-16 text-center text-white sm:px-6 sm:py-20 lg:px-8"><div class="mx-auto max-w-4xl"><span class="text-xs font-bold uppercase tracking-widest text-tertiary-fixed">Growing Filipino MSMEs together</span><h2 class="mt-3 font-headline text-4xl font-extrabold leading-tight sm:text-5xl">Hindi mo kailangang mag-isa. Sumama sa pinakamalaking komunidad ng negosyanteng Pilipino.</h2><p class="mx-auto mt-5 max-w-3xl leading-7 text-white/80">Join a practical ecosystem built to help Filipino entrepreneurs learn faster, connect better, and grow sustainably.</p><div class="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a class="inline-flex justify-center rounded-full bg-secondary px-7 py-4 font-bold text-white hover:bg-secondary-container" href="/membership#registration">Join FLAME PH Free →</a><a class="inline-flex justify-center rounded-full bg-white/10 px-7 py-4 font-bold text-white hover:bg-white/20" href="/membership/more-benefits">Get More MSME Benefits</a></div></div></section>
</main>
@include('partials.home-footer')
@include('partials.mobile-navigation')
<script>
const audienceCopy={aspiring:['Turn Your Idea Into a Profitable Enterprise','Receive straightforward roadmaps for registration, product costing, supplier matchmaking, and free AI marketing copy generators.','/membership#registration','Launch Your Business →'],existing:['Build Better Systems for Your Existing MSME','Access practical tools for costing, POS, marketing, vendor savings, and member referrals.','/learn','Explore Business Tools →'],professional:['Share Expertise That Moves Entrepreneurs Forward','Connect with MSMEs who need professional guidance in finance, marketing, technology, and operations.','/events','Become a Mentor →'],mentor:['Teach, Inspire, and Grow Local Leaders','Join workshops, chapters, and mentorship circles that turn experience into community impact.','/events','Join the Mentor Network →'],corporate:['Partner With a Nationwide MSME Ecosystem','Build meaningful market linkages, community programs, and shared growth initiatives with FLAME PH.','/about#partners','Partner With FLAME PH →'],chapter:['Pioneer a FLAME Chapter in Your Province','Lead local entrepreneurs with chapter charters, workshop curriculum, and nationwide support.','/events','Start a Chapter →']};
document.querySelectorAll('.audience-tab').forEach((tab)=>tab.addEventListener('click',()=>{document.querySelectorAll('.audience-tab').forEach((item)=>item.classList.remove('is-active','!bg-primary','!text-white'));tab.classList.add('is-active','!bg-primary','!text-white');const [title,description,href,label]=audienceCopy[tab.dataset.audience];document.querySelector('#audience-title').textContent=title;document.querySelector('#audience-description').textContent=description;const link=document.querySelector('#audience-link');link.href=href;link.textContent=label;}));
</script>
</body>
</html>
