@extends('admin.layouts.panel')

@section('title', 'Admin accounts')

@section('content')
<div class="admin-topbar"><div><p style="margin:0 0 5px;color:#bc000c;font-weight:700;letter-spacing:.08em;text-transform:uppercase;font-size:12px">FLAME PH • ACCESS CONTROL</p><h1 class="admin-brand" style="margin:0;font-size:32px">Admin accounts</h1><p style="margin:7px 0 0;color:#5c6070">Founder manages all roles; super admins can manage regular admins and basic users only.</p></div><div class="admin-nav"><a href="{{ route('admin.dashboard') }}">Dashboard</a><a class="secondary" href="{{ route('admin.profile') }}">My profile</a><form method="POST" action="{{ route('admin.logout') }}">@csrf<button class="admin-button">Log out</button></form></div></div>
<section class="admin-card" style="margin-bottom:18px"><h2 class="admin-brand" style="margin:0 0 15px;font-size:22px">Create admin account</h2><form method="POST" action="{{ route('admin.accounts.create') }}" class="admin-grid">@csrf
<div class="admin-field"><label for="new-admin-name">Full name</label><input id="new-admin-name" name="name" required maxlength="120" value="{{ old('name') }}"></div>
<div class="admin-field"><label for="new-admin-email">Email</label><input id="new-admin-email" type="email" name="email" required maxlength="254" value="{{ old('email') }}"></div>
<div class="admin-field"><label for="new-admin-role">Role</label><select id="new-admin-role" name="role" required>@foreach($roles as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
<div class="admin-field"><label for="new-admin-password">Temporary password (12+ characters)</label><div class="admin-password-control"><input id="new-admin-password" type="password" name="password" minlength="12" required autocomplete="new-password"><button class="admin-password-toggle" type="button" data-admin-password-toggle aria-label="Show password" aria-pressed="false" title="Show password"><span class="material-symbols-outlined" aria-hidden="true">visibility</span></button></div></div>
<div class="admin-field"><label for="new-admin-password-confirmation">Confirm password</label><div class="admin-password-control"><input id="new-admin-password-confirmation" type="password" name="password_confirmation" minlength="12" required autocomplete="new-password"><button class="admin-password-toggle" type="button" data-admin-password-toggle aria-label="Show password" aria-pressed="false" title="Show password"><span class="material-symbols-outlined" aria-hidden="true">visibility</span></button></div></div>
<div style="align-self:end;margin-bottom:14px"><button class="admin-button" type="submit">Create account</button></div>
</form><p style="margin:0;color:#737685;font-size:13px">No invitation or password-reset email is sent yet. Send initial credentials privately and require each admin to use a unique password.</p></section>
<section class="admin-card"><h2 class="admin-brand" style="margin:0 0 14px;font-size:22px">Existing accounts</h2><div class="admin-table-wrap"><table class="admin-table" style="min-width:1000px"><thead><tr><th>Name / Email</th><th>Member registration</th><th>Role and rights</th><th>Access</th><th>Last sign-in</th><th>Actions</th></tr></thead><tbody>
@foreach($accounts as $account)
@php($canManageTarget = $admin->role === 'founder' || ($admin->role === 'super_admin' && in_array($account->role, ['regular_admin','basic_user'], true)))
<tr><td>@if($account->avatar_path)<img src="{{ route('admin.accounts.avatar',$account) }}" alt="" style="width:38px;height:38px;object-fit:cover;border-radius:50%;margin-bottom:5px">@endif<br><strong>{{ $account->name }}</strong><br><span style="color:#737685">{{ $account->email }}</span><br><span style="color:#737685">Sponsored: {{ $account->sponsored_by ?: '—' }} · Invited: {{ $account->invited_by ?: '—' }}<br>Hired/appointed by: {{ $account->hired_by ?: '—' }} · Date: {{ $account->hired_at?->format('Y-m-d') ?: '—' }}</span></td><td>{{ $memberSinceByEmail->get(strtolower($account->email))?->format('Y-m-d') ?? 'Not linked to a member account' }}</td><td>{{ \App\Models\AdminAccount::ROLES[$account->role] ?? $account->role }}<details><summary style="cursor:pointer;color:#003289">List admin rights</summary><ul style="padding-left:18px">@foreach($account->rights() as $right)<li>{{ $right }}</li>@endforeach</ul></details></td><td>{{ $account->active ? 'Active' : 'Disabled' }}</td><td>{{ $account->last_login_at?->format('Y-m-d H:i') ?? 'Never' }}</td><td>
@if($canManageTarget)
<details><summary style="cursor:pointer;color:#003289;font-weight:700">Edit profile / access</summary><form method="POST" enctype="multipart/form-data" action="{{ route('admin.accounts.update', $account) }}" style="min-width:280px;padding-top:12px">@csrf @method('PATCH')
<div class="admin-field"><label>Name</label><input name="name" value="{{ $account->name }}" required maxlength="120"></div><div class="admin-field"><label>Email</label><input type="email" name="email" value="{{ $account->email }}" required maxlength="254"></div><div class="admin-field"><label>Role</label><select name="role" required>@foreach($roles as $key => $label)<option value="{{ $key }}" @selected($account->role === $key)>{{ $label }}</option>@endforeach</select></div><div class="admin-field"><label>Access</label><select name="active"><option value="1" @selected($account->active)>Active</option><option value="0" @selected(!$account->active)>Disabled</option></select></div><div class="admin-field"><label>Choose Avatar or Upload Photo</label><input type="file" name="avatar" accept="image/jpeg,image/png,image/webp"></div><div class="admin-field"><label>Sponsored by</label><input name="sponsored_by" maxlength="160" value="{{ $account->sponsored_by }}"></div><div class="admin-field"><label>Invited by</label><input name="invited_by" maxlength="160" value="{{ $account->invited_by }}"></div><div class="admin-field"><label>Hired / appointed by</label><input name="hired_by" maxlength="160" value="{{ $account->hired_by }}"></div><div class="admin-field"><label>Hired / appointed date</label><input type="date" name="hired_at" value="{{ $account->hired_at?->format('Y-m-d') }}"></div><button class="admin-button">Save profile / access</button></form>
<details style="margin-top:10px"><summary style="cursor:pointer;color:#003289;font-weight:700">Change password</summary><form method="POST" action="{{ route('admin.accounts.password',$account) }}" style="min-width:250px;padding-top:10px">@csrf<div class="admin-field"><label>New password (12+ characters)</label><div class="admin-password-control"><input type="password" name="password" required minlength="12" autocomplete="new-password"><button class="admin-password-toggle" type="button" data-admin-password-toggle aria-label="Show password" aria-pressed="false" title="Show password"><span class="material-symbols-outlined" aria-hidden="true">visibility</span></button></div></div><div class="admin-field"><label>Confirm password</label><div class="admin-password-control"><input type="password" name="password_confirmation" required minlength="12" autocomplete="new-password"><button class="admin-password-toggle" type="button" data-admin-password-toggle aria-label="Show password" aria-pressed="false" title="Show password"><span class="material-symbols-outlined" aria-hidden="true">visibility</span></button></div></div><button class="admin-button">Change password</button></form></details>
@if(!$account->is($admin))<form method="POST" action="{{ route('admin.accounts.delete', $account) }}" style="margin-top:9px" onsubmit="return confirm('Delete this admin account?')">@csrf @method('DELETE')<button class="admin-button" style="background:#a4000a">Delete account</button></form>@endif
</details>
@else<span style="color:#737685">Managed by founder</span>@endif
</td></tr>
@endforeach
</tbody></table></div></section>
@endsection
